services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: colegio
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"

  web:
    build: .
    depends_on:
      - db