# Generated by Django 6.0.6 on 2026-07-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='qr',
            field=models.ImageField(blank=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cursoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estadoMatricula',
            field=models.TextField(blank=True, choices=[('Matriculado', 'Matriculado'), ('No Matriculado', 'No Matriculado'), ('Retirado', 'Retirado'), ('Graduado', 'Graduado'), ('Sancionado', 'Sancionado')], max_length=20, null=True),
        ),
    ]
